- name: Deploy to EC2
  uses: appleboy/ssh-action@v1
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}
    debug: true

    script: |
      echo "===== USER ====="
      whoami

      echo "===== HOST ====="
      hostname

      echo "===== DOCKER ====="
      docker --version || true

      echo "===== COMPOSE ====="
      docker compose version || true

      echo "===== AWS ====="
      aws --version || true

      echo "===== APP ====="
      ls -la ~/app || true