name: Deploy Backend

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: <ECR_REPOSITORY>

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t yt-comment-analysis-plugin .

      - name: Tag Docker Image
        run: |
          docker tag yt-comment-analysis-plugin:latest \
          016647419459.dkr.ecr.${AWS_REGION}.amazonaws.com/yt-comment-analysis-plugin:latest

      - name: Push Docker Image
        run: |
          docker push \
          016647419459.dkr.ecr.${AWS_REGION}.amazonaws.com/yt-comment-analysis-plugin:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            aws ecr get-login-password \
            --region ${AWS_REGION} \
            | docker login \
            --username AWS \
            --password-stdin \
            016647419459.dkr.ecr.${AWS_REGION}.amazonaws.com

            cd ~/app

            docker compose pull

            docker compose up -d

            docker image prune -f